Name: Rex::OS::Base
Description: Base module to install and configure basic os packages
Author: jan gehring <jan.gehring@gmail.com>
License: Apache 2.0
Requires:
  Rex::Ext::ParamLookup:
    git: https://bitbucket.org/jfried/rex-ext-paramlookup.git
    branch: master
